//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreFront.DATA.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class BooksTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BooksTable()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
        }
    
        public int BookID { get; set; }
        public string BooksTitle { get; set; }
        public int GenreID { get; set; }
        public int AuthorID { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> UnitsSold { get; set; }
        public Nullable<System.DateTime> PublishDate { get; set; }
        public Nullable<int> Publisher { get; set; }
        public int StockID { get; set; }
        public Nullable<int> CategoryID { get; set; }
    
        public virtual AuthorTable AuthorTable { get; set; }
        public virtual GenreIDTable GenreIDTable { get; set; }
        public virtual Publisher Publisher1 { get; set; }
        public virtual Stock Stock { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
    }
}
